version: '3.1'
services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
  db:
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: initial
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql